from pydantic import BaseModel, Field

class CarIn(BaseModel):
    vin_id: str = Field()
    epc: str = Field()
    epc_id: str = Field()
    model_year_from_vin: str = Field()
    model_year: str = Field()
    made_in: str = Field()
    model_detail: str = Field()
    brand: str = Field()
    factory: str = Field()
    series: str = Field()
    model: str = Field()
    sales_version: str = Field()
    capacity: str = Field()
    engine_no: str = Field()
    kilowatt: str = Field()
    horse_power: str = Field()
    air_intake: str = Field()
    fuel_type: str = Field()
    transmission_detail: str = Field()
    gear_num: str = Field()
    driving_mode: str = Field()
    door_num: str = Field()
    seat_num: str = Field()
    body_type: str = Field()
    price: str = Field()
    price_unit: str = Field()

class PartIn(BaseModel):
    name: str = Field()
    epc: str = Field()
    brand_name: str = Field()
    group_id: str = Field()
    price: str = Field()
    part_number: str = Field()
    img_src: str = Field()

